version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  assignees:
  - brentonhouse
  labels:
  - dependencies
  - dependabot
  versioning-strategy: increase
  allow:
  - dependency-type: direct
  ignore:
  - dependency-name: should
    versions:
    - ">= 0"
